'use strict';
const raceState={steps:[0,0,0,0,0],winner:null,leader:null,finish:100,player:null,phase:'choose',elapsed:0,combo:0,lastBeat:-1};
const raceButtons=[...document.querySelectorAll('.character')],raceOrder=[2,4,1,0,3];let frame=0,lastTime=0,candidate=null,candidateSince=0,fadeToken=0,musicMuted=false,opponentSpeeds=[];
const modeButton=document.createElement('button');modeButton.id='race-mode-toggle';modeButton.textContent='MUSIC ROOM';document.querySelector('.header-right').prepend(modeButton);
const raceLayer=document.createElement('div');raceLayer.className='race-layer';raceLayer.innerHTML='<div class="race-hud"><strong>♥ ♥ ♥</strong><span id="race-message" role="status">Choose your runner</span><button id="race-reset">RESTART</button></div><div class="race-lanes" aria-hidden="true"></div><div class="finish-line" aria-hidden="true"><span>FINISH</span></div><div class="race-music"><span id="race-now">PICK YOUR RUNNER</span><button id="race-pause" aria-label="Toggle music">♫</button></div><div class="race-start-panel"><p id="runner-choice">Tap a character to cheer for her.</p><button id="start-race" disabled>START RACE</button><button id="open-album">MEMORIES <span id="album-count">0/4</span></button></div><div class="rhythm-controls" hidden><span id="race-time">0:00</span><button id="rhythm-tap" aria-label="Tap on the beat"><span class="beat-ring"></span><b>CHEER</b></button><span id="rhythm-feedback" role="status">Tap as the ring closes</span><button id="pause-race">PAUSE</button></div>';
stage.append(raceLayer);const lanes=raceLayer.querySelector('.race-lanes');[3,2,0,4,1].forEach(i=>{const lane=document.createElement('div');lane.className='race-lane';lane.style.setProperty('--lane-color',tracks[i].color);lane.innerHTML=`<span class="lane-progress" id="lane-progress-${i}"></span><span class="lane-count" id="lane-count-${i}">0%</span>`;lanes.append(lane)});
function layoutRace(){if(!stage.classList.contains('race-mode'))return;raceButtons.forEach((b,i)=>{b.style.setProperty('left',(7+raceState.steps[i]/100*73)+'%','important');b.style.setProperty('top',(17+raceOrder[i]*12)+'%','important');b.style.setProperty('width','12%','important');b.style.setProperty('height','13%','important');b.classList.toggle('your-runner',i===raceState.player);document.getElementById('lane-progress-'+i).style.width=raceState.steps[i]+'%';document.getElementById('lane-count-'+i).textContent=Math.floor(raceState.steps[i])+'%';b.setAttribute('aria-label',`${tracks[i].tag} runner, ${Math.floor(raceState.steps[i])} percent`)});}
raceButtons.forEach((b,i)=>b.addEventListener('click',e=>{if(!stage.classList.contains('race-mode'))return;e.stopImmediatePropagation();if(raceState.phase==='choose'){raceState.player=i;document.getElementById('runner-choice').textContent=tracks[i].tag+' · Your runner';document.getElementById('start-race').disabled=false;layoutRace();}else if(raceState.phase==='running'&&i===raceState.player)cheer();},true));
function musicFor(i,instant=false){const token=++fadeToken;if(instant){audio.volume=1;select(i,!musicMuted);return;}const initial=audio.volume,t0=performance.now();function down(now){if(token!==fadeToken)return;audio.volume=Math.max(0,Math.min(1,initial*(1-(now-t0)/300)));if(now-t0<300)requestAnimationFrame(down);else{select(i,!musicMuted);audio.volume=0;const t1=performance.now();function up(t){if(token!==fadeToken)return;audio.volume=Math.max(0,Math.min(1,(t-t1)/450));if(t-t1<450)requestAnimationFrame(up);}requestAnimationFrame(up)}}requestAnimationFrame(down);}
function checkLeader(){const best=Math.max(...raceState.steps);let next=raceState.leader;if(next===null||raceState.steps[next]<best-.01)next=raceState.steps.indexOf(best);if(next===raceState.leader){candidate=null;return;}if(candidate!==next){candidate=next;candidateSince=raceState.elapsed;}else if(raceState.elapsed-candidateSince>=2){raceState.leader=next;musicFor(next);candidate=null;}document.getElementById('race-now').textContent='LEADING · '+tracks[raceState.leader??raceState.player].title;}
function beginRace(){if(raceState.player===null)return;raceState.phase='running';opponentSpeeds=tracks.map(()=>2.55+Math.random()*.3);raceState.leader=raceState.player;musicMuted=false;musicFor(raceState.player,true);document.getElementById("race-now").textContent="LEADING · "+tracks[raceState.player].title;raceLayer.querySelector('.race-start-panel').hidden=true;raceLayer.querySelector('.rhythm-controls').hidden=false;document.getElementById('race-message').textContent='Follow the ring · Cheer for your runner';lastTime=performance.now();frame=requestAnimationFrame(tick);}
function tick(now){if(raceState.phase!=='running')return;const dt=Math.min(.1,(now-lastTime)/1000);lastTime=now;raceState.elapsed+=dt;raceState.steps.forEach((_,i)=>{const speed=i===raceState.player?2.12:opponentSpeeds[i]+.16*Math.sin(raceState.elapsed*.8+i);raceState.steps[i]=Math.min(raceState.elapsed<30?99:100,raceState.steps[i]+speed*dt)});const phase=(raceState.elapsed%.8)/.8;document.getElementById('rhythm-tap').style.setProperty('--beat-scale',1+(1-phase)*.65);document.getElementById('race-time').textContent=time(raceState.elapsed);stage.classList.toggle('final-sprint',raceState.elapsed>=27);checkLeader();layoutRace();let winner=raceState.steps.findIndex(s=>s>=100);if(raceState.elapsed>=42)winner=raceState.steps.indexOf(Math.max(...raceState.steps));if(winner>=0){finishRace(winner);return;}frame=requestAnimationFrame(tick);}
function cheer(){if(raceState.phase!=='running')return;const beat=Math.round(raceState.elapsed/.8);if(beat===raceState.lastBeat)return;raceState.lastBeat=beat;const distance=Math.abs(raceState.elapsed-beat*.8);let text='MISS',boost=0;if(distance<=.11){text='PERFECT';boost=1.1;raceState.combo++;}else if(distance<=.23){text='GOOD';boost=.6;raceState.combo++;}else raceState.combo=0;raceState.steps[raceState.player]=Math.min(raceState.elapsed<30?99:100,raceState.steps[raceState.player]+boost);document.getElementById('rhythm-feedback').textContent=text+(raceState.combo?' ×'+raceState.combo:'');document.getElementById('rhythm-feedback').dataset.grade=text;layoutRace();}
function finishRace(winner){raceState.phase='finished';raceState.winner=winner;raceState.leader=winner;raceState.steps[winner]=100;cancelAnimationFrame(frame);musicFor(winner);document.getElementById('race-message').textContent=winner===raceState.player?'YOU WIN!':'A close race · Try again!';layoutRace();document.dispatchEvent(new CustomEvent('race-finished',{detail:{winner,player:raceState.player}}));}
function resetRace(){cancelAnimationFrame(frame);++fadeToken;audio.pause();audio.volume=1;audio.currentTime=0;Object.assign(raceState,{steps:[0,0,0,0,0],winner:null,leader:null,player:null,phase:'choose',elapsed:0,combo:0,lastBeat:-1});candidate=null;document.dispatchEvent(new Event('race-reset'));raceLayer.querySelector('.race-start-panel').hidden=false;raceLayer.querySelector('.rhythm-controls').hidden=true;document.getElementById('start-race').disabled=true;document.getElementById('runner-choice').textContent='Tap a character to cheer for her.';document.getElementById('race-message').textContent='Choose your runner';document.getElementById('race-now').textContent='PICK YOUR RUNNER';document.getElementById('rhythm-feedback').textContent='Tap as the ring closes';document.getElementById('pause-race').textContent='PAUSE';stage.classList.remove('final-sprint');musicCard.hidden=true;layoutRace();}
function pauseRace(){if(raceState.phase==='running'){raceState.phase='paused';cancelAnimationFrame(frame);++fadeToken;audio.volume=1;audio.pause();document.getElementById('pause-race').textContent='RESUME';}else if(raceState.phase==='paused'){raceState.phase='running';if(!musicMuted)musicFor(raceState.leader,true);lastTime=performance.now();frame=requestAnimationFrame(tick);document.getElementById('pause-race').textContent='PAUSE';}}
function setRaceMode(enabled){resetRace();stage.classList.toggle('race-mode',enabled);modeButton.textContent=enabled?'MUSIC ROOM':'RACE MODE';referenceArt.src='room-reference-clean.png';if(enabled)layoutRace();else alignReferenceCharacters();}
modeButton.onclick=()=>setRaceMode(!stage.classList.contains('race-mode'));document.getElementById('start-race').onclick=beginRace;document.getElementById('rhythm-tap').onclick=cheer;document.getElementById('pause-race').onclick=pauseRace;document.getElementById('race-reset').onclick=resetRace;document.getElementById('race-pause').onclick=()=>{musicMuted=!musicMuted;if(musicMuted)audio.pause();else if(raceState.leader!==null&&raceState.phase!=='paused')start();document.getElementById('race-pause').textContent=musicMuted?'♪ OFF':'♫ ON'};
document.addEventListener('keydown',e=>{if(e.code==='Space'&&raceState.phase==='running'&&!e.repeat&&stage.classList.contains('race-mode')&&!document.querySelector('dialog[open]')&&!['BUTTON','INPUT','SUMMARY'].includes(document.activeElement.tagName)){e.preventDefault();cheer()}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&raceState.phase==='running')pauseRace()});document.getElementById('replay-intro').addEventListener('click',()=>{if(raceState.phase==='running')pauseRace()});
audio.addEventListener('ended',e=>{if(!stage.classList.contains('race-mode'))return;e.stopImmediatePropagation();if(raceState.leader!==null&&!musicMuted){audio.currentTime=0;start()}},true);
document.addEventListener('room-track-selected',()=>{if(stage.classList.contains('race-mode'))musicCard.hidden=true});new ResizeObserver(layoutRace).observe(stage);stage.classList.add('race-mode');layoutRace();



