'use strict';
const raceState={steps:[0,0,0,0,0],winner:null,leader:null,finish:20};
const raceButtons=[...document.querySelectorAll('.character')],raceOrder=[2,4,1,0,3];
const modeButton=document.createElement('button');modeButton.id='race-mode-toggle';modeButton.textContent='MUSIC ROOM';document.querySelector('.header-right').prepend(modeButton);
const raceLayer=document.createElement('div');raceLayer.className='race-layer';raceLayer.innerHTML='<div class="race-hud"><strong>♥ ♥ ♥</strong><span id="race-message" role="status">Tap a runner · Move 1–3 steps · First to 20 wins</span><button id="race-reset">RESTART</button></div><div class="race-lanes" aria-hidden="true"></div><div class="finish-line" aria-hidden="true"><span>FINISH</span></div><div class="race-music"><span id="race-now">PICK YOUR RUNNER</span><button id="race-pause" aria-label="Play or pause music">▶</button></div><div class="race-winner" hidden><span>★ WINNER ★</span><strong id="winner-name"></strong><button id="race-again">RACE AGAIN</button></div>';
stage.append(raceLayer);
const lanes=raceLayer.querySelector('.race-lanes');[3,2,0,4,1].forEach(i=>{const lane=document.createElement('div');lane.className='race-lane';lane.style.setProperty('--lane-color',tracks[i].color);lane.innerHTML=`<span class="lane-progress" id="lane-progress-${i}"></span><span class="lane-count" id="lane-count-${i}">0 / 20</span>`;lanes.append(lane)});
raceButtons.forEach((button,i)=>{const badge=document.createElement('span');badge.className='step-badge';badge.setAttribute('aria-hidden','true');button.append(badge);button.addEventListener('click',e=>{if(!stage.classList.contains('race-mode'))return;e.stopImmediatePropagation();if(raceState.winner!==null)return;const roll=1+Math.floor(Math.random()*3),before=raceState.steps[i];raceState.steps[i]=Math.min(raceState.finish,before+roll);badge.textContent='+'+(raceState.steps[i]-before);button.classList.remove('is-running');void button.offsetWidth;button.classList.add('is-running');clearTimeout(button.raceTimer);button.raceTimer=setTimeout(()=>button.classList.remove('is-running'),500);updateLeaderMusic();musicCard.hidden=true;document.getElementById('race-message').textContent=`${tracks[i].tag} +${raceState.steps[i]-before} · ${raceState.steps[i]} / 20`;layoutRace();if(raceState.steps[i]===raceState.finish){raceState.winner=i;document.getElementById('winner-name').textContent=tracks[i].tag+' WINS!';document.dispatchEvent(new CustomEvent('race-finished',{detail:{winner:i}}));raceButtons.forEach(b=>b.setAttribute('aria-disabled','true'));document.getElementById('race-message').textContent=tracks[i].tag+' wins! Start a new race to play again.';}},true);});
function layoutRace(){if(!stage.classList.contains('race-mode'))return;raceButtons.forEach((button,i)=>{button.style.setProperty('left',(7+raceState.steps[i]/20*73)+'%','important');button.style.setProperty('top',(18+raceOrder[i]*14)+'%','important');button.style.setProperty('width','12%','important');button.style.setProperty('height','14%','important');document.getElementById('lane-progress-'+i).style.width=(raceState.steps[i]/20*100)+'%';document.getElementById('lane-count-'+i).textContent=raceState.steps[i]+' / 20';button.setAttribute('aria-label',`${tracks[i].tag} runner, ${tracks[i].title}, ${raceState.steps[i]} of 20 steps`);});}
function resetRace(){raceState.steps.fill(0);raceState.winner=null;raceState.leader=null;document.dispatchEvent(new Event("race-reset"));audio.pause();audio.currentTime=0;musicCard.hidden=true;raceLayer.querySelector('.race-winner').hidden=true;raceButtons.forEach(b=>{b.setAttribute('aria-disabled','false');b.classList.remove('is-running','selected','card-anchor')});document.getElementById('race-now').textContent='PICK YOUR RUNNER';document.getElementById('race-message').textContent='Tap a runner · Move 1–3 steps · First to 20 wins';layoutRace();}
function setRaceMode(enabled){stage.classList.toggle('race-mode',enabled);musicCard.hidden=true;modeButton.textContent=enabled?'MUSIC ROOM':'RACE MODE';referenceArt.src='room-reference-clean.png';if(enabled){layoutRace();updateLeaderMusic(false);}else{raceButtons.forEach((b,i)=>{b.removeAttribute('aria-disabled');b.setAttribute('aria-label','Play '+tracks[i].title)});alignReferenceCharacters();}}
modeButton.onclick=()=>setRaceMode(!stage.classList.contains('race-mode'));
document.getElementById('race-reset').onclick=resetRace;document.getElementById('race-again').onclick=resetRace;
document.getElementById('race-pause').onclick=()=>{if(raceState.leader===null)return;if(audio.paused)updateLeaderMusic(true);else audio.pause()};
function syncRaceMusic(){document.getElementById('race-pause').textContent=audio.paused?'▶':'Ⅱ';if(!audio.paused)document.getElementById('race-now').textContent=tracks[current].title;}
audio.addEventListener('play',syncRaceMusic);audio.addEventListener('pause',syncRaceMusic);document.addEventListener('room-track-selected',()=>{if(stage.classList.contains('race-mode'))musicCard.hidden=true});
function updateLeaderMusic(play=true){const best=Math.max(...raceState.steps);if(best===0){raceState.leader=null;audio.pause();document.getElementById('race-now').textContent='PICK YOUR RUNNER';return;}let leader=raceState.leader;if(leader===null||raceState.steps[leader]<best)leader=raceState.steps.indexOf(best);const changed=leader!==raceState.leader||current!==leader;raceState.leader=leader;if(changed)select(leader,play);else if(play&&audio.paused)start();document.getElementById('race-now').textContent='LEADING · '+tracks[leader].title;}
audio.addEventListener('ended',e=>{if(!stage.classList.contains('race-mode'))return;e.stopImmediatePropagation();if(raceState.leader!==null){audio.currentTime=0;updateLeaderMusic(true)}},true);
document.getElementById('enter-room').addEventListener('click',()=>{if(stage.classList.contains('race-mode'))updateLeaderMusic(false)});
document.getElementById('surprise-enter').addEventListener('click',()=>{if(stage.classList.contains('race-mode'))updateLeaderMusic(false)});
new ResizeObserver(layoutRace).observe(stage);setRaceMode(true);
