'use strict';
const memoryDialog=document.createElement('dialog');memoryDialog.className='memory-camera';memoryDialog.setAttribute('aria-label','Winner memory camera');memoryDialog.innerHTML='<canvas class="fireworks" aria-hidden="true"></canvas><div class="camera-body"><header class="camera-top"><span>NEWJEANS <small>MEMORY CAM · 35mm</small></span><span class="camera-led">● REC</span><button id="memory-close" aria-label="Close winner photo">×</button></header><div class="camera-viewfinder"><img id="winner-photo" alt="A randomly selected NewJeans memory photo"><span class="viewfinder-tag" id="memory-winner"></span><span class="photo-counter" id="photo-counter"></span></div><footer class="camera-bottom"><span>ONE RACE. ONE MEMORY.<small>KEEP THIS MOMENT ♡</small></span><button id="camera-again">RACE AGAIN</button><button id="firework-replay" aria-label="Replay celebration fireworks">✦</button></footer></div>';
document.body.append(memoryDialog);
let particleFrame=0,burstTimers=[],lastPhoto=-1;
let collected=[];try{const saved=JSON.parse(localStorage.getItem('nj-memory-album')||'[]');if(Array.isArray(saved))collected=[...new Set(saved.filter(n=>Number.isInteger(n)&&n>=0&&n<4))];}catch{}
function syncAlbum(){document.getElementById('album-count').textContent=collected.length+'/4';}
syncAlbum();
function stopFireworks(){cancelAnimationFrame(particleFrame);burstTimers.forEach(clearTimeout);burstTimers=[];const c=memoryDialog.querySelector('canvas');c.getContext('2d').clearRect(0,0,c.width,c.height);}
function fireworks(){stopFireworks();if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const canvas=memoryDialog.querySelector('canvas'),ctx=canvas.getContext('2d'),box=memoryDialog.getBoundingClientRect();canvas.width=Math.round(box.width);canvas.height=Math.round(box.height);const particles=[];const colors=['#ffe99a','#ff95d1','#96e7ff','#aff8b0','#d7a8ff'];const burst=(x,y)=>{for(let j=0;j<55;j++){const a=Math.random()*Math.PI*2,s=1.5+Math.random()*4;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:65+Math.random()*25,color:colors[j%5]})}};[[.15,.25],[.8,.3],[.5,.12],[.2,.7],[.85,.72]].forEach(([x,y],i)=>burstTimers.push(setTimeout(()=>burst(x*canvas.width,y*canvas.height),i*320)));let previous=performance.now();const startTime=previous;function frame(now){const dt=Math.min(2,(now-previous)/16.67);previous=now;ctx.clearRect(0,0,canvas.width,canvas.height);for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;if(p.life<=0){particles.splice(i,1);continue;}p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=.035*dt;p.vx*=.985;p.vy*=.99;ctx.globalAlpha=Math.min(1,p.life/30);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,2.2,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;if(now-startTime<4500)particleFrame=requestAnimationFrame(frame);else stopFireworks();}particleFrame=requestAnimationFrame(frame);}
document.addEventListener('race-finished',e=>{const unseen=[0,1,2,3].filter(i=>!collected.includes(i));let photo=unseen.length?unseen[Math.floor(Math.random()*unseen.length)]:Math.floor(Math.random()*4);if(!unseen.length&&photo===lastPhoto)photo=(photo+1+Math.floor(Math.random()*3))%4;const isNew=!collected.includes(photo);lastPhoto=photo;if(isNew)collected.push(photo);try{localStorage.setItem('nj-memory-album',JSON.stringify(collected))}catch{}syncAlbum();document.getElementById('winner-photo').src=`0${photo+1}.jpg`;document.getElementById('memory-winner').textContent=tracks[e.detail.winner].tag+' WINS!';document.getElementById('photo-counter').textContent=`${isNew?"NEW MEMORY · ":""}COLLECTED ${collected.length}/4`;if(!memoryDialog.open)memoryDialog.showModal();fireworks();});
memoryDialog.addEventListener('close',()=>{stopFireworks();document.getElementById('race-reset').focus()});document.getElementById('memory-close').onclick=()=>memoryDialog.close();document.getElementById('camera-again').onclick=()=>{memoryDialog.close();resetRace()};document.getElementById('firework-replay').onclick=fireworks;document.addEventListener('race-reset',()=>{if(memoryDialog.open)memoryDialog.close();stopFireworks()});

const album=document.createElement('dialog');album.className='album-dialog';album.innerHTML='<header><h2>YOUR MEMORIES</h2><button id="close-album" aria-label="Close album">×</button></header><div class="album-grid"></div><p>Saved on this device · Finish a race to collect a memory.</p>';document.body.append(album);document.getElementById('close-album').onclick=()=>album.close();document.getElementById('open-album').onclick=()=>{const grid=album.querySelector('.album-grid');grid.replaceChildren();for(let i=0;i<4;i++){const card=document.createElement('button');card.disabled=!collected.includes(i);card.innerHTML=card.disabled?'<span>?</span><small>NOT YET FOUND</small>':'<img alt="Collected memory '+(i+1)+'" src="0'+(i+1)+'.jpg"><small>MEMORY 0'+(i+1)+'</small>';card.onclick=()=>{document.getElementById('winner-photo').src='0'+(i+1)+'.jpg';document.getElementById('memory-winner').textContent='YOUR COLLECTION';document.getElementById('photo-counter').textContent='MEMORY 0'+(i+1);memoryDialog.showModal();};grid.append(card)}album.showModal()};

document.addEventListener("race-reset",()=>{if(album.open)album.close()});

